### ISSUE TITLE
Multiple API instances can share the same Resource

### ISSUE THREAD

**Issue by swinkels-at-basf** [JorisBenschop/qrest#20]
For the ResourceConfig objects with an explicit processor defined, the processor gets instantiated when the module is loaded, where for the other ResourceConfig objects, the processor is instantiated during the _init_ of the API object (https://github.com/JorisBenschop/qrest/blob/development/qrest/resource.py#L50). Therefor, a second API object from the same config module will share some Resource objects with the first API object.

So it is currently not possible to create two independent API objects from the same imported config module.

**Comment by swinkels-at-basf** [comment]
I would think that user expects that each API instance has its own Resource instances, regardless of whether the processor was instantiated on the config or not. That expectation make it a bug.

**Comment by swinkels-at-basf** [comment]
On the other hand, one could say that it was never intended to have multiple API instances and to support it would be a new feature. Let me think about possible use cases.

**Comment by JorisBenschop** [comment]
Its only a bug because this specific user tries to modify the config files at runtime, which is not how qrest was intended to be used.

**Comment by swinkels-at-basf** [comment]
You made the initial design so I won't argue how you intended it to be used :)

What we do see is that the configuration leaks into the runtime: the processor instance that is used for configuration is also the one active at runtime. From a technical point of view that is something we can address relatively easily. I would like to know the use cases and if there are other changes required to support that. FYI, the use case that lead to this issue is the simultaneous use of different server URLs for the same API.

**Comment by swinkels-at-basf** [comment]
This issue has been addressed by pull request https://github.com/JorisBenschop/qrest/pull/21,
